---
title: Ben Cheetham
timezone: Europe/London
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    read_time: true
description: local gov digital
baseurl: 
url: https://ben.cheetham.me.uk
twitter_username: BforBen
github_username: bforben
disqus_shortname: bforben
analytics: UA-89904-3
locale: en
paginate: 10
paginate_path: "/blog/page/:num/"
safe: true
lsi: false
highlighter: rouge
markdown: kramdown
permalink: "/blog/:year/:month/:title"
exclude:
- compile.sh
- CONTRIBUTING.md
- Gemfile
- Gemfile.lock
- Makefile
- lint.go
- README.md
- tools
- vendor
- CNAME
kramdown:
  auto_ids: true,
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: true
coderay:
  coderay_wrap: div
  coderay_line_numbers: ''
  coderay_line_numbers_start: 1
  coderay_tab_width: 4
  coderay_bold_every: 10
  coderay_css: style
sass:
  style: compressed
gems:
- jekyll-feed
- jekyll-redirect-from
- jekyll-seo-tag
- jekyll-sitemap
